name: Keep Render Backend Warm

on:
  schedule:
    - cron: "*/10 * * * *" # runs every 10 minutes
  workflow_dispatch: # allows manual run from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render backend
        run: |
          echo "Pinging backend..."
          curl -i https://journal-backend-prod-qbom.onrender.com/public/health
